// test_tts.js
const path = require('path');
const fs = require('fs');

// Load .env from the same directory as this script
require('dotenv').config({ path: path.join(__dirname, '.env') }); 

// Require the exported instance from audioHandler.js
try {
  const audioHandler = require('./audioHandler.js'); // This should now be the instance

  // テスト用のテキストとユーザーID
  const sampleText = "これは標準のOpenAI TTSモデル（tts-1）のテスト音声です。";
  const dummyUserId = "test-tts-user-001";

  async function runTest() {
    console.log(`テスト開始: \"${sampleText}\" を音声に変換します...`);

    // Check if OPENAI_API_KEY is loaded
    if (!process.env.OPENAI_API_KEY) {
        console.error("エラー: OPENAI_API_KEY が .env ファイルから読み込めていません。");
        console.error(`${path.join(__dirname, '.env')} ファイルが存在するか、キーが設定されているか確認してください。`);
        return;
    } else {
        console.log("OPENAI_API_KEY が読み込まれました。");
    }

    try {
      // synthesizeSpeech internally calls _synthesizeSegment which saves the file
      const result = await audioHandler.synthesizeSpeech(sampleText, dummyUserId);

      if (result && result.filePath && result.buffer) {
        console.log("音声合成成功！");
        // Assuming result.filePath is an absolute path generated by audioHandler
        const absoluteFilePath = result.filePath;
        console.log("生成されたファイルの絶対パス:", absoluteFilePath);
        
        // Check file existence using the absolute path
        if (fs.existsSync(absoluteFilePath)) {
            console.log("ファイルが存在することを確認しました。");
            console.log("バッファサイズ:", result.buffer.length, "bytes");
            // Hint for playing the file
            console.log(`\nヒント: macOSの場合、ターミナルで \`open \"${absoluteFilePath}\"\` を実行すると音声を聞けます。`);
        } else {
            console.error("エラー: ファイルパスは取得できましたが、ファイルが存在しません。パスを確認してください:", absoluteFilePath);
        }

      } else if (result && result.limitExceeded) {
          console.error("エラー: 音声リクエストの制限に達しました。");
          console.error(result.limitMessage);
      }
       else {
        console.error("エラー: 音声合成に失敗しました。結果オブジェクト:", result);
      }
    } catch (error) {
      console.error("テスト中にエラーが発生しました:", error);
    }
  }

  runTest();

} catch (error) {
  if (error.code === 'MODULE_NOT_FOUND') {
    console.error("エラー: audioHandler.js が見つかりません。パスを確認してください。");
    console.error("試行したパス: ./audioHandler.js (test_tts.jsからの相対パス)");
  } else {
    console.error("スクリプトの初期化中に予期せぬエラーが発生しました:", error);
  }
  process.exit(1);
} 